# Generated by Django 3.2.5 on 2021-08-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210824_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_phpto',
            new_name='car_photo',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_phpto_1',
            new_name='car_photo_1',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_phpto_2',
            new_name='car_photo_2',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_phpto_3',
            new_name='car_photo_3',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_phpto_4',
            new_name='car_photo_4',
        ),
    ]
